/**
 * @(#)CommonsLoggingTest.java - Will's practices of Project OpenSourceStudy.
 */
package net.will.opensourcestudy.commonslogging;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * Related configuration files:
 * classpath: commons-logging.properties
 * classpath: simplelog.properties
 * 
 * @author Will
 * @version 2011-12-7
 */
public class CommonsLoggingTest {
	private final Log logger = LogFactory.getLog(getClass());
	
	public Log getLogger() {
		return logger;
	}

	public static void main(String[] args) {
		// enable some diagnostic information generated by commons-logging
		System.setProperty("org.apache.commons.logging.diagnostics.dest", "STDOUT");
		
		CommonsLoggingTest test = new CommonsLoggingTest();
		testLoggerPriority(test.getLogger());
		
		DefaultLoggingLevelTest defaultlevel = new DefaultLoggingLevelTest();
		testLoggerPriority(defaultlevel.getLogger());
	}
	
	public static void testLoggerPriority(Log logger) {
		if (logger.isTraceEnabled()) {
			logger.trace("This is a trace log.");
		}
		if (logger.isDebugEnabled()) {
			logger.debug("This is a debug log.");
		}
		if (logger.isInfoEnabled()) {
			logger.info("This is a info log.");
		}
		if (logger.isWarnEnabled()) {
			logger.warn("This is a warn log.");
		}
		if (logger.isErrorEnabled()) {
			logger.error("This is a error log.");
		}
		if (logger.isFatalEnabled()) {
			logger.fatal("This is a fatal log.");
		}
	}

}

class DefaultLoggingLevelTest {
	private final Log logger = LogFactory.getLog("DefaultLoggingLevelTest");
	
	public Log getLogger() {
		return logger;
	}
}
